### ISSUE TITLE
How are stringmap files generated?

### ISSUE THREAD

**Issue by a361570441** [ouwou/deadlockery#2]

**Comment by ouwou** [comment]
https://github.com/ouwou/deadlockery/blob/master/deadlock-dumper/main.cpp
theyre CUtlStringTokens in the engine. you can also derive them with `MurmurHash2("upgrade_magic_carpet", 0x31415926)` 
the cpp will crash on latest version but if u want i can update it

**Comment by a361570441** [comment]
please update it, i want to get them, thanks a lot !!!
